Adds support for ByteStrings in inside JSON
well-typed/cborg pull request #254
Opened 2020-12-18 16:04 UTC by yaitskov

I am implementing WebAuthn authentication.
Chrome browser returns part of data encoded in CBOR and uses 58/59 bytes (fixed byte string with length up to 255/65535 bytes) to encode key.

I think exposing such type as a hex string in JSON is best option.
Aeson.Array Number is much less efficient.

+ extra dependency on base16

2020-12-18 16:10 UTC, yaitskov commented
@phadej

2020-12-18 17:03 UTC, phadej commented
I don't understand why I'm pinged here.

2020-12-18 18:22 UTC, yaitskov commented
I was looking for reviewers and found you among previous ones.

2020-12-18 18:23 UTC, phadej commented
That's the way I ended up "maintaining" plenty of stuff :)

2020-12-18 18:36 UTC, yaitskov commented
CI is green except on gch 7.8.4 because store package dropped 7.8.4 support
```
9883f44 - Remove configuration for building with ghc-7.8 (4 months ago) (Michael Sloan)
```

2020-12-18 18:38 UTC, phadej commented
could `store` maintainers correct the metadata then: https://matrix.hackage.haskell.org/#/package/store, there shouldn't be red cells.

2020-12-18 19:24 UTC, phadej commented
Please, let's not workaround other bugs (which are easily fixable). There is no hurry.

2020-12-21 07:45 UTC, yaitskov commented
PR CI is green, thanks to store team efforts.
https://github.com/mgsloan/store/issues/157

2021-02-23 01:18 UTC, dcoutts requested changes
Yes, the CBOR/JSON support wehave should cover byte strings. That said, I think as a default we should follow the CBOR RFC as our spec. It says:

https://tools.ietf.org/html/rfc7049#section-4.1

>    o  A byte string (major type 2) that is not embedded in a tag that specifies a proposed encoding is encoded in base64url without padding and becomes a JSON string.

There are also tags for hex, but it sounds like your application just uses raw cbor bytestrings.

If that's ok for your application that's great. If not and you really want to use hex, then I think the thing we should think about is how to do cusomised non-default conversions that are not exactly the conversions that the RFC specifies.

2023-04-27 13:24 UTC, merged